[cpu]
max_processes = 1

[pages]
contentOnlyPages = ["about"]

[posts]
excludeDirs = ["drafts", "latex", "templates"]

[server]
addr = "localhost:9000"

[style]
[style.codeBlock]
enable = false
style = "xcode-dark"
